"""add address and position to user

Revision ID: 3ae5851d0191
Revises: 00a6a096702a
Create Date: 2025-04-23 15:13:20.350447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae5851d0191'
down_revision = '00a6a096702a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user2', schema=None) as batch_op:
        batch_op.drop_column('position')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
