"""increase avatar_url length

Revision ID: 3e95aa983239
Revises: 7bcb87532d8a
Create Date: 2025-05-23 21:32:41.433347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e95aa983239'
down_revision = '7bcb87532d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user2', schema=None) as batch_op:
        batch_op.alter_column('avatar_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user2', schema=None) as batch_op:
        batch_op.alter_column('avatar_url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
