"""Add full_itinerary_data column to history table

Revision ID: 65efa5755feb
Revises: 2a9defafb947
Create Date: 2025-05-29 22:26:06.180547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65efa5755feb'
down_revision = '2a9defafb947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_itinerary_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_column('full_itinerary_data')
    # ### end Alembic commands ###
