"""Add Facebook OAuth fields to users

Revision ID: 7bcb87532d8a
Revises: 3b16b4306f73
Create Date: 2025-05-23 20:03:18.986478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bcb87532d8a'
down_revision = '3b16b4306f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['facebook_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user2', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('provider')
        batch_op.drop_column('facebook_id')

    # ### end Alembic commands ###
