"""add destination_images table

Revision ID: c49715e6d6e1
Revises: 0427af25a549
Create Date: 2025-04-16 23:24:49.104335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49715e6d6e1'
down_revision = '0427af25a549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    op.drop_table('destination_images')
    # ### end Alembic commands ###
